"""Initial migration

Revision ID: 38a707fa94b7
Revises:
Create Date: 2025-01-06 15:11:50.341462

"""

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy.vector import VECTOR

# revision identifiers, used by Alembic.
revision = "38a707fa94b7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.String(), nullable=False),
        sa.Column("document_name", sa.String(), nullable=False),
        sa.Column("chunk_text", sa.String(), nullable=False),
        sa.Column("extra_metadata", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("UP_TO_DATE", "OUTDATED", "DELETED", native_enum=False),
            nullable=False,
        ),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ollama_bge_m3_embeddings",
        sa.Column("embedding", VECTOR(dim=1024), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chunk_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["document_chunks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ollama_bge_m3_embeddings_embedding",
        "ollama_bge_m3_embeddings",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "public.vector_cosine_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_ollama_bge_m3_embeddings_embedding",
        table_name="ollama_bge_m3_embeddings",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "public.vector_cosine_ops"},
    )
    op.drop_table("ollama_bge_m3_embeddings")
    op.drop_table("document_chunks")
    # ### end Alembic commands ###
