"""Add description to themes

Revision ID: 3c5dcd7ace53
Revises: de9238ac5b4e
Create Date: 2025-01-16 00:49:15.906165

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3c5dcd7ace53"
down_revision = "de9238ac5b4e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("themes", sa.Column("description", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("themes", "description")
    # ### end Alembic commands ###
