"""Add document_name to DocumentChunk

Revision ID: 8f0a47955710
Revises: bc539b61f96c
Create Date: 2024-12-20 18:06:13.325830

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8f0a47955710"
down_revision = "bc539b61f96c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_chunks",
        sa.Column(
            "document_name", sa.String(), nullable=False, server_default="UNKNOWN"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_chunks", "document_name")
    # ### end Alembic commands ###
