"""Add index to DocumentChunk

Revision ID: bc539b61f96c
Revises: e2eabfd25378
Create Date: 2024-12-20 17:31:42.218054

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "bc539b61f96c"
down_revision = "e2eabfd25378"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_document_chunks_embedding", "document_chunks", ["embedding"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_document_chunks_embedding", table_name="document_chunks")
    # ### end Alembic commands ###
